# Generated by Django 5.2.6 on 2026-10-01 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioPage',
            fields=[
                ('slug', models.SlugField(choices=[('home', 'Home'), ('about', 'About'), ('projects', 'Projects'), ('blog', 'Blog'), ('contact', 'Contact')], max_length=32, primary_key=True, serialize=False)),
                ('eyebrow', models.CharField(blank=True, max_length=120)),
                ('title', models.CharField(max_length=240)),
                ('description', models.TextField(blank=True)),
                ('section_title', models.CharField(blank=True, max_length=240)),
                ('section_description', models.TextField(blank=True)),
                ('secondary_title', models.CharField(blank=True, max_length=240)),
                ('secondary_description', models.TextField(blank=True)),
                ('cta_title', models.CharField(blank=True, max_length=240)),
                ('cta_description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('key', models.CharField(default='site', editable=False, max_length=32, primary_key=True, serialize=False)),
                ('default_theme', models.CharField(choices=[('blue', 'Blue'), ('light', 'Light'), ('purple', 'Purple'), ('green', 'Green'), ('minimal', 'Minimal'), ('sunset', 'Sunset')], default='blue', max_length=16)),
            ],
        ),
    ]
