# Generated by Django 5.2.6 on 2026-10-03 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoliopage',
            name='show_in_navigation',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='portfoliopage',
            name='sort_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='portfoliopage',
            name='slug',
            field=models.SlugField(max_length=32, primary_key=True, serialize=False),
        ),
    ]
