from django.db import migrations,models
class Migration(migrations.Migration):
    initial=True
    dependencies=[]
    operations=[
        migrations.CreateModel(name="Profile",fields=[("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),("name",models.CharField(max_length=160)),("headline",models.CharField(max_length=200)),("bio",models.TextField()),("location",models.CharField(blank=True,max_length=160)),("email",models.EmailField(max_length=254)),("avatar",models.ImageField(blank=True,null=True,upload_to="profile/")),("cv",models.FileField(blank=True,null=True,upload_to="cv/")),("github_url",models.URLField(blank=True)),("linkedin_url",models.URLField(blank=True)),("website_url",models.URLField(blank=True))]),
        migrations.CreateModel(name="Skill",fields=[("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),("name",models.CharField(max_length=100)),("category",models.CharField(choices=[("Frontend","Frontend"),("Backend","Backend"),("Database","Database"),("DevOps","DevOps"),("Architecture","Architecture"),("Tools","Tools")],max_length=40)),("level",models.PositiveSmallIntegerField(default=80)),("sort_order",models.PositiveIntegerField(default=0))]),
        migrations.CreateModel(name="Experience",fields=[("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),("company",models.CharField(max_length=160)),("role",models.CharField(max_length=160)),("description",models.TextField()),("start_date",models.DateField()),("end_date",models.DateField(blank=True,null=True)),("sort_order",models.PositiveIntegerField(default=0))]),
        migrations.CreateModel(name="Tag",fields=[("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),("name",models.CharField(max_length=80,unique=True)),("slug",models.SlugField(max_length=50,unique=True))]),
        migrations.CreateModel(name="Project",fields=[("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),("title",models.CharField(max_length=180)),("slug",models.SlugField(max_length=50,unique=True)),("summary",models.CharField(max_length=300)),("description",models.TextField()),("image",models.ImageField(blank=True,null=True,upload_to="projects/")),("live_url",models.URLField(blank=True)),("repo_url",models.URLField(blank=True)),("featured",models.BooleanField(default=False)),("sort_order",models.PositiveIntegerField(default=0)),("created_at",models.DateTimeField(auto_now_add=True)),("updated_at",models.DateTimeField(auto_now=True)),("tags",models.ManyToManyField(blank=True,related_name="projects",to="portfolio.tag"))])]
