# Generated by Django 5.2.6 on 2026-10-01 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='experience',
            options={'ordering': ['sort_order', '-start_date']},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['sort_order', '-created_at']},
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['sort_order', 'name']},
        ),
    ]
